# Generated by Django 5.0.7 on 2024-08-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognews',
            options={'verbose_name': 'Blog News', 'verbose_name_plural': 'Blog-News'},
        ),
    ]
