# Generated by Django 5.0.7 on 2024-08-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_blognews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('blog_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.blognews')),
            ],
        ),
    ]
