# Generated by Django 5.0.7 on 2024-08-21 16:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='tags',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=30000),
        ),
    ]
